-- CRIANDO A DATABESE
CREATE DATABASE LIVRARIA;

-- CRIANDO A TABELA DENTRO DA DATA BASE (JÁ COM A PRIMARY KEY QUE TORNA TODO O RESGRISTRO EM UMA REFERENCIA SÓ SOMADO COM O AUTO_INCREMENT PARA SER AUTOMÁTICO)
-- DENTRO DA CRIANÇÃO DA TABELA JÁ I
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

-- JÁ EM SOSSA SEGUNDA TABELA TEMOS OS TERMOS FOREIGN KEY QUE É A NOSSA CHAVE EXTRANGEIRA PARA REFERENCIA A OUTRA TABELA E SIGNIFICAR QUE ESSA TABELA EM QUESTÃO DEPENDE DE OUTRA.
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CELL') NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

-- NA TERCEIRA TABELA TAMBEM FAZENDO O FOREIGN KEY JUNTO COM O REFERENCES.
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	PAIS VARCHAR(20) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	RUA VARCHAR(20) NOT NULL,
	CASA VARCHAR(20) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','CELIA@IG.COM','5767876889');

INSERT INTO ENDERECO VALUES(NULL,'BRASIL', 'FE', 'FEZINHA', 'CAPONGA', 'SUA MAE','89',4);
INSERT INTO ENDERECO VALUES(NULL,'BRASIL', 'CE', 'FORTALEZA', 'MARACANAU', 'RUA CAPITAO HERMES','69A',1);
INSERT INTO ENDERECO VALUES(NULL,'ARGENTINA', 'PI', 'POLINOMIUS', 'HH', 'RUA DA CACHORRA MAGA','666Q',3);
INSERT INTO ENDERECO VALUES(NULL,'UEA', 'US', 'MANJERICAO', 'PRIMA', 'RUA NEGAL','AA11',2);
INSERT INTO ENDERECO VALUES(NULL,'PORTUGAL', 'IP', ' NOBRE', 'LÁ DE CIMA', 'RUA NEGATIBO','6677',6);
INSERT INTO ENDERECO VALUES(NULL,'AFEGANISTÃO', 'PA', 'NEGADO', 'VILA DA FOLHA', '13C','650',5);

INSERT INTO TELEFONE VALUES(NULL,'CELL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CELL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CELL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CELL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CELL','88687909',2);

-- UNIR 3 TABELAS, PRECISA COLOCAR OS 'PONTOS' POR QUE NÃO PODE REPETIR O NOME DAS COLUNAS

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE 
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

--AQUI SÓ TEM UMA LETRA ANTES DOS PONTOS POIS COLOCAMOS APELIDOS EM CADA UMA DAS TABELAS

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;

--VIEW (PARA GUARDAR QUERY PARA NÃO PRECISAR DIGITAR TUDO SEMPRE)

CREATE VIEW V_RELATORIO AS
SELECT  C.NOME, 
		C.SEXO, 
		IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS "E-MAIL", 
		T.TIPO, 
		T.NUMERO, 
		E.BAIRRO, 
		E.CIDADE, 
		E.ESTADO
FROM CLIENTE C 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;
-- 'V_' PARA DIZER QUE ELE É UM VIEW POIS QUANDO FOR DAR UM SHOW, ELE APARECE JUNTO DAS TABLES

-- TÁBEM PODEMOS FAZER UM FILTRO NAS VIEWS.
SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;

-- CRIANDO UMA PROCEDURE
-- PRECISAMOS TROCAR O DELIMITADOR DE COMANDOS PARA PODERMOS CRIAR PROCEDURES POIS TEMOS UMA PROGRAMAÇÃO DENTRO DE UM COMANDO
DELIMITER $

CREATE PROCEDURE NOME_EMPRESA()
BEGIN
	
	SELECT 'EXEMPLOS DO W.DAVID' AS EMPRESA;

END
$

/* CHAMANDO UMA PROCEDURE */

DELIMITER ;

CALL NOME_EMPRESA();

/* PROCEDURES COM PARAMETROS */
DELIMITER $

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
	
	SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100,50)$
CALL CONTA(345634,4354)$
CALL CONTA(55654,56760)$
CALL CONTA(45646,6766)$
